## Calculating similarity score using TFIDF Vectorizer.

In [1]:
!pip install docx2txt

  Created wheel for docx2txt: filename=docx2txt-0.8-py3-none-any.whl size=3980 sha256=db3cbffab93b02230bb0296e4f71b9398d6e6294d9aaa64be2080248e5a173fd
  Stored in directory: /root/.cache/pip/wheels/b7/20/b2/473e3aea9a0c0d3e7b2f7bd81d06d0794fec12752733d1f3a8
Successfully built docx2txt


In [2]:
!pip install strsimpy

     |████████████████████████████████| 45 kB 2.3 MB/s 


In [3]:
# importing all necessary libraries
import pandas as pd
import numpy as np
import docx2txt
import json, collections
from pandas.io.json import json_normalize
import os

In [4]:
!pip install docx2csv

     |████████████████████████████████| 5.6 MB 7.9 MB/s 
  Created wheel for python-docx: filename=python_docx-0.8.11-py3-none-any.whl size=184507 sha256=4bc08cb6ae91d7b1e9e8f0f2a405184bde23156186f165fc24204cb77679fab3
  Stored in directory: /root/.cache/pip/wheels/f6/6f/b9/d798122a8b55b74ad30b5f52b01482169b445fbb84a11797a6
Successfully built python-docx


In [5]:
from docx2csv import extract_tables, extract
tables = extract_tables('/content/lists.docx')

In [6]:
import pandas as pd
import sklearn as sk
import numpy as np
import re
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from docx import Document
document = Document("/content/lists.docx")

In [7]:
def read_docx_table(document,table_num):
  table = document.tables[table_num-1]
  data = [[cell.text for cell in row.cells] for row in table.rows]
  df = pd.DataFrame(data)
  return df

In [8]:
table_num=1
df = read_docx_table(document,table_num)
df.head()

0                                                  1
0  P1  Analyze a complex computing problem and to app...
1  P2  Design, implement, and evaluate a computing-ba...
2  P3  Communicate effectively in a variety of profes...
3  P4  Recognize professional responsibilities and ma...
4  P5  Function effectively as a member or leader of ...

In [9]:
q1 = df.copy()

In [10]:
df[1][0]

'Analyze a complex computing problem and to apply principles of computing and other relevant disciplines to identify solutions.'

In [11]:
table_num=2
df1 = read_docx_table(document,table_num)
df1.head()

0                                                  1
0  C1                     Explain how AI impacts society
1  C2        Apply AI methods to perform practical tasks
2  C3                      Synthesize a simple AI system
3  C4  Evaluate different AI approaches to solve a pr...
4  C5  Explain the basic principles of the data minin...

In [12]:
p1 = df1.copy()
p2 = df1.copy()
p3 = df1.copy()
p4 = df1.copy()
p5 = df1.copy()
p6 = df1.copy()

In [13]:
df[1][5]

'Apply computer science theory and software development fundamentals to produce computing-based solutions.'

In [14]:
p1.loc[-1] = ["CC", "Analyze a complex computing problem and to apply principles of computing and other relevant disciplines to identify solutions."]  # adding a row
p1.index = p1.index + 1  # shifting index
p1.sort_index(inplace=True) 
p1.head()

0                                                  1
0  CC  Analyze a complex computing problem and to app...
1  C1                     Explain how AI impacts society
2  C2        Apply AI methods to perform practical tasks
3  C3                      Synthesize a simple AI system
4  C4  Evaluate different AI approaches to solve a pr...

In [15]:
p2.loc[-1] = ["CC", "Design, implement, and evaluate a computing-based solution to meet a given set of computing requirements in the context of the program’s discipline."]  # adding a row
p2.index = p2.index + 1  # shifting index
p2.sort_index(inplace=True) 
p2.head()

0                                                  1
0  CC  Design, implement, and evaluate a computing-ba...
1  C1                     Explain how AI impacts society
2  C2        Apply AI methods to perform practical tasks
3  C3                      Synthesize a simple AI system
4  C4  Evaluate different AI approaches to solve a pr...

In [16]:
p3.loc[-1] = ["CC", "Communicate effectively in a variety of professional contexts."]  # adding a row
p3.index = p3.index + 1  # shifting index
p3.sort_index(inplace=True) 
p3.head()

0                                                  1
0  CC  Communicate effectively in a variety of profes...
1  C1                     Explain how AI impacts society
2  C2        Apply AI methods to perform practical tasks
3  C3                      Synthesize a simple AI system
4  C4  Evaluate different AI approaches to solve a pr...

In [17]:
p4.loc[-1] = ["CC", "Recognize professional responsibilities and make informed judgments in computing practice based on legal and ethical principles."]  # adding a row
p4.index = p4.index + 1  # shifting index
p4.sort_index(inplace=True) 
p4.head()

0                                                  1
0  CC  Recognize professional responsibilities and ma...
1  C1                     Explain how AI impacts society
2  C2        Apply AI methods to perform practical tasks
3  C3                      Synthesize a simple AI system
4  C4  Evaluate different AI approaches to solve a pr...

In [18]:
p5.loc[-1] = ["CC", "Function effectively as a member or leader of a team engaged in activities appropriate to the program’s discipline."]  # adding a row
p5.index = p5.index + 1  # shifting index
p5.sort_index(inplace=True) 
p5.head()

0                                                  1
0  CC  Function effectively as a member or leader of ...
1  C1                     Explain how AI impacts society
2  C2        Apply AI methods to perform practical tasks
3  C3                      Synthesize a simple AI system
4  C4  Evaluate different AI approaches to solve a pr...

In [19]:
p6.loc[-1] = ["CC", "Apply computer science theory and software development fundamentals to produce computing-based solutions."]  # adding a row
p6.index = p6.index + 1  # shifting index
p6.sort_index(inplace=True) 
p6.head()

0                                                  1
0  CC  Apply computer science theory and software dev...
1  C1                     Explain how AI impacts society
2  C2        Apply AI methods to perform practical tasks
3  C3                      Synthesize a simple AI system
4  C4  Evaluate different AI approaches to solve a pr...

In [20]:
p6.shape

(133, 2)

In [21]:
p1[1] = p1[1].str.lower()
corpus = p1[1].tolist()
corpus

['analyze a complex computing problem and to apply principles of computing and other relevant disciplines to identify solutions.',
 'explain how ai impacts society',
 'apply ai methods to perform practical tasks',
 'synthesize a simple ai system',
 'evaluate different ai approaches to solve a problem',
 'explain the basic principles of the data mining process.',
 'prepare data for mining and exploration',
 'use data mining techniques and modern tools to discover trends and patterns in realistic datasets',
 'evaluate different data mining models/techniques with respect to their performance accuracy.',
 'function on teams and communicate effectively in written and oral forms.',
 'explain techniques of mathematical models.',
 'design models for simple and complex problems.',
 'model discrete event systems.',
 'use simulation software to solve complicated problems.',
 'evaluate the performance of different systems using simulation techniques.',
 'describe the main components of a machine l

In [22]:
p2[1] = p2[1].str.lower()
corpus1 = p2[1].tolist()
corpus1

['design, implement, and evaluate a computing-based solution to meet a given set of computing requirements in the context of the program’s discipline.',
 'explain how ai impacts society',
 'apply ai methods to perform practical tasks',
 'synthesize a simple ai system',
 'evaluate different ai approaches to solve a problem',
 'explain the basic principles of the data mining process.',
 'prepare data for mining and exploration',
 'use data mining techniques and modern tools to discover trends and patterns in realistic datasets',
 'evaluate different data mining models/techniques with respect to their performance accuracy.',
 'function on teams and communicate effectively in written and oral forms.',
 'explain techniques of mathematical models.',
 'design models for simple and complex problems.',
 'model discrete event systems.',
 'use simulation software to solve complicated problems.',
 'evaluate the performance of different systems using simulation techniques.',
 'describe the main com

In [23]:
p3[1] = p3[1].str.lower()
corpus2 = p3[1].tolist()
corpus2

['communicate effectively in a variety of professional contexts.',
 'explain how ai impacts society',
 'apply ai methods to perform practical tasks',
 'synthesize a simple ai system',
 'evaluate different ai approaches to solve a problem',
 'explain the basic principles of the data mining process.',
 'prepare data for mining and exploration',
 'use data mining techniques and modern tools to discover trends and patterns in realistic datasets',
 'evaluate different data mining models/techniques with respect to their performance accuracy.',
 'function on teams and communicate effectively in written and oral forms.',
 'explain techniques of mathematical models.',
 'design models for simple and complex problems.',
 'model discrete event systems.',
 'use simulation software to solve complicated problems.',
 'evaluate the performance of different systems using simulation techniques.',
 'describe the main components of a machine learning system.',
 'design training sets and testing sets for ma

In [24]:
p4[1] = p4[1].str.lower()
corpus3 = p4[1].tolist()
corpus3

['recognize professional responsibilities and make informed judgments in computing practice based on legal and ethical principles.',
 'explain how ai impacts society',
 'apply ai methods to perform practical tasks',
 'synthesize a simple ai system',
 'evaluate different ai approaches to solve a problem',
 'explain the basic principles of the data mining process.',
 'prepare data for mining and exploration',
 'use data mining techniques and modern tools to discover trends and patterns in realistic datasets',
 'evaluate different data mining models/techniques with respect to their performance accuracy.',
 'function on teams and communicate effectively in written and oral forms.',
 'explain techniques of mathematical models.',
 'design models for simple and complex problems.',
 'model discrete event systems.',
 'use simulation software to solve complicated problems.',
 'evaluate the performance of different systems using simulation techniques.',
 'describe the main components of a machine

In [25]:
p5[1] = p5[1].str.lower()
corpus4 = p5[1].tolist()
corpus4

['function effectively as a member or leader of a team engaged in activities appropriate to the program’s discipline.',
 'explain how ai impacts society',
 'apply ai methods to perform practical tasks',
 'synthesize a simple ai system',
 'evaluate different ai approaches to solve a problem',
 'explain the basic principles of the data mining process.',
 'prepare data for mining and exploration',
 'use data mining techniques and modern tools to discover trends and patterns in realistic datasets',
 'evaluate different data mining models/techniques with respect to their performance accuracy.',
 'function on teams and communicate effectively in written and oral forms.',
 'explain techniques of mathematical models.',
 'design models for simple and complex problems.',
 'model discrete event systems.',
 'use simulation software to solve complicated problems.',
 'evaluate the performance of different systems using simulation techniques.',
 'describe the main components of a machine learning sys

In [26]:
p6[1] = p6[1].str.lower()
corpus5= p6[1].tolist()
corpus5

['apply computer science theory and software development fundamentals to produce computing-based solutions.',
 'explain how ai impacts society',
 'apply ai methods to perform practical tasks',
 'synthesize a simple ai system',
 'evaluate different ai approaches to solve a problem',
 'explain the basic principles of the data mining process.',
 'prepare data for mining and exploration',
 'use data mining techniques and modern tools to discover trends and patterns in realistic datasets',
 'evaluate different data mining models/techniques with respect to their performance accuracy.',
 'function on teams and communicate effectively in written and oral forms.',
 'explain techniques of mathematical models.',
 'design models for simple and complex problems.',
 'model discrete event systems.',
 'use simulation software to solve complicated problems.',
 'evaluate the performance of different systems using simulation techniques.',
 'describe the main components of a machine learning system.',
 'd

In [28]:
tfidf_vectorizer = TfidfVectorizer(stop_words='english', use_idf=True)
corpii = tfidf_vectorizer.fit_transform(corpus)
corpii1 = tfidf_vectorizer.fit_transform(corpus1)
corpii2 = tfidf_vectorizer.fit_transform(corpus2)
corpii3 = tfidf_vectorizer.fit_transform(corpus3)
corpii4 = tfidf_vectorizer.fit_transform(corpus4)
corpii5 = tfidf_vectorizer.fit_transform(corpus5)
print(tfidf_vectorizer.get_feature_names())

['accuracy', 'ai', 'algebra', 'algorithm', 'algorithmic', 'algorithms', 'analysis', 'analyze', 'analyzing', 'animation', 'animations', 'apis', 'applicability', 'application', 'applications', 'apply', 'approach', 'approaches', 'appropriate', 'architectures', 'array', 'arrays', 'aspects', 'assess', 'based', 'basic', 'bioinformatics', 'biological', 'biology', 'build', 'case', 'centered', 'choose', 'class', 'classes', 'client', 'code', 'communicate', 'communication', 'communities', 'compare', 'complete', 'completeness', 'completion', 'complex', 'complexity', 'complicated', 'components', 'computational', 'computer', 'computing', 'concepts', 'constructs', 'containing', 'continuing', 'control', 'controls', 'create', 'crime', 'current', 'customize', 'cyberspace', 'data', 'database', 'datasets', 'decision', 'define', 'defined', 'delivering', 'demonstrate', 'design', 'determine', 'develop', 'development', 'diagram', 'different', 'digital', 'dimension', 'dimensions', 'discover', 'discrete', 'disc

/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [29]:
corpii.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.47144428, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.41267413, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [30]:
corpii1.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.47144428, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.41195898, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [31]:
corpii2.toarray()
corpii3.toarray()
corpii4.toarray()
corpii5.toarray()

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.47144428, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.41267413, 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [32]:
X1 = pd.DataFrame(corpii.toarray())
X1.head()

0         1    2    3    4    5    6    ...  324  325  326  327  328  329  330
0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.471444  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.412674  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.553357  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.436721  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[5 rows x 331 columns]

In [33]:
X2 = pd.DataFrame(corpii1.toarray())
X2.head()

0         1    2    3    4    5    6    ...  325  326  327  328  329  330  331
0  0.0  0.000000  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.471444  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.411959  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.553357  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.435652  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0

[5 rows x 332 columns]

In [34]:
X2 = pd.DataFrame(corpii1.toarray())
X3 = pd.DataFrame(corpii2.toarray())
X4 = pd.DataFrame(corpii3.toarray())
X5 = pd.DataFrame(corpii4.toarray())
X6 = pd.DataFrame(corpii5.toarray())

In [35]:
from sklearn.metrics.pairwise import cosine_similarity
dd1 = pd.DataFrame(cosine_similarity(X1, dense_output=True))
dd1.head()

0         1         2         3    ...       129       130  131  132
0  1.000000  0.000000  0.056216  0.000000  ...  0.206364  0.047298  0.0  0.0
1  0.000000  1.000000  0.194553  0.260877  ...  0.000000  0.000000  0.0  0.0
2  0.056216  0.194553  1.000000  0.228356  ...  0.000000  0.252627  0.0  0.0
3  0.000000  0.260877  0.228356  1.000000  ...  0.000000  0.000000  0.0  0.0
4  0.098929  0.205889  0.180223  0.241662  ...  0.000000  0.281498  0.0  0.0

[5 rows x 133 columns]

In [36]:
dd2 = pd.DataFrame(cosine_similarity(X2, dense_output=True))
dd2.head()

0         1         2         3    ...       129       130  131  132
0  1.000000  0.000000  0.000000  0.000000  ...  0.419068  0.000000  0.0  0.0
1  0.000000  1.000000  0.194216  0.260877  ...  0.000000  0.000000  0.0  0.0
2  0.000000  0.194216  1.000000  0.227960  ...  0.000000  0.254795  0.0  0.0
3  0.000000  0.260877  0.227960  1.000000  ...  0.000000  0.000000  0.0  0.0
4  0.073639  0.205386  0.179471  0.241071  ...  0.000000  0.280465  0.0  0.0

[5 rows x 133 columns]

In [37]:
dd3 = pd.DataFrame(cosine_similarity(X3, dense_output=True))
dd3.head()

0         1         2         3    ...  129       130  131       132
0  1.0  0.000000  0.000000  0.000000  ...  0.0  0.000000  0.0  0.113315
1  0.0  1.000000  0.194216  0.260877  ...  0.0  0.000000  0.0  0.000000
2  0.0  0.194216  1.000000  0.227960  ...  0.0  0.254795  0.0  0.000000
3  0.0  0.260877  0.227960  1.000000  ...  0.0  0.000000  0.0  0.000000
4  0.0  0.204576  0.178763  0.240121  ...  0.0  0.279359  0.0  0.000000

[5 rows x 133 columns]

In [38]:
dd4 = pd.DataFrame(cosine_similarity(X4, dense_output=True))
dd4.head()

0         1         2         3    ...       129       130  131  132
0  1.0  0.000000  0.000000  0.000000  ...  0.100962  0.000000  0.0  0.0
1  0.0  1.000000  0.194216  0.260877  ...  0.000000  0.000000  0.0  0.0
2  0.0  0.194216  1.000000  0.227960  ...  0.000000  0.254795  0.0  0.0
3  0.0  0.260877  0.227960  1.000000  ...  0.000000  0.000000  0.0  0.0
4  0.0  0.204576  0.178763  0.240121  ...  0.000000  0.279359  0.0  0.0

[5 rows x 133 columns]

In [39]:
dd5 = pd.DataFrame(cosine_similarity(X5, dense_output=True))
dd5.head()

0         1         2         3    ...       129       130  131       132
0  1.0  0.000000  0.000000  0.000000  ...  0.111386  0.000000  0.0  0.165684
1  0.0  1.000000  0.194216  0.260877  ...  0.000000  0.000000  0.0  0.000000
2  0.0  0.194216  1.000000  0.227960  ...  0.000000  0.254795  0.0  0.000000
3  0.0  0.260877  0.227960  1.000000  ...  0.000000  0.000000  0.0  0.000000
4  0.0  0.204576  0.178763  0.240121  ...  0.000000  0.279359  0.0  0.000000

[5 rows x 133 columns]

In [40]:
dd6 = pd.DataFrame(cosine_similarity(X6, dense_output=True))
dd6.head()

0         1         2         3    ...      129       130       131  132
0  1.000000  0.000000  0.065387  0.000000  ...  0.25947  0.333255  0.222608  0.0
1  0.000000  1.000000  0.194553  0.260877  ...  0.00000  0.000000  0.000000  0.0
2  0.065387  0.194553  1.000000  0.228356  ...  0.00000  0.257176  0.000000  0.0
3  0.000000  0.260877  0.228356  1.000000  ...  0.00000  0.000000  0.000000  0.0
4  0.000000  0.204576  0.179074  0.240121  ...  0.00000  0.284739  0.000000  0.0

[5 rows x 133 columns]

In [41]:
dd1.rename(columns = {0 :'P1'}, inplace = True)
dd1.head()

P1         1         2         3  ...       129       130  131  132
0  1.000000  0.000000  0.056216  0.000000  ...  0.206364  0.047298  0.0  0.0
1  0.000000  1.000000  0.194553  0.260877  ...  0.000000  0.000000  0.0  0.0
2  0.056216  0.194553  1.000000  0.228356  ...  0.000000  0.252627  0.0  0.0
3  0.000000  0.260877  0.228356  1.000000  ...  0.000000  0.000000  0.0  0.0
4  0.098929  0.205889  0.180223  0.241662  ...  0.000000  0.281498  0.0  0.0

[5 rows x 133 columns]

In [42]:
dd2.rename(columns = {0 :'P2'}, inplace = True)
dd3.rename(columns = {0 :'P3'}, inplace = True)
dd4.rename(columns = {0 :'P4'}, inplace = True)
dd5.rename(columns = {0 :'P5'}, inplace = True)
dd6.rename(columns = {0 :'P6'}, inplace = True)

In [43]:
d = pd.concat([dd1['P1'], dd2['P2'], dd3['P3'], dd4['P4'], dd5['P5'], dd6['P6']], axis=1)
d.head()

P1        P2   P3   P4   P5        P6
0  1.000000  1.000000  1.0  1.0  1.0  1.000000
1  0.000000  0.000000  0.0  0.0  0.0  0.000000
2  0.056216  0.000000  0.0  0.0  0.0  0.065387
3  0.000000  0.000000  0.0  0.0  0.0  0.000000
4  0.098929  0.073639  0.0  0.0  0.0  0.000000

In [44]:
dd2 = d[1:]
dd2.head()

P1        P2   P3        P4   P5        P6
1  0.000000  0.000000  0.0  0.000000  0.0  0.000000
2  0.056216  0.000000  0.0  0.000000  0.0  0.065387
3  0.000000  0.000000  0.0  0.000000  0.0  0.000000
4  0.098929  0.073639  0.0  0.000000  0.0  0.000000
5  0.091348  0.000000  0.0  0.089383  0.0  0.000000

In [45]:
dd2.reset_index(inplace = True)
dd2.head()

index        P1        P2   P3        P4   P5        P6
0      1  0.000000  0.000000  0.0  0.000000  0.0  0.000000
1      2  0.056216  0.000000  0.0  0.000000  0.0  0.065387
2      3  0.000000  0.000000  0.0  0.000000  0.0  0.000000
3      4  0.098929  0.073639  0.0  0.000000  0.0  0.000000
4      5  0.091348  0.000000  0.0  0.089383  0.0  0.000000

In [46]:
dd2.drop(['index'], axis=1, inplace = True)
dd2.head()

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,


P1        P2   P3        P4   P5        P6
0  0.000000  0.000000  0.0  0.000000  0.0  0.000000
1  0.056216  0.000000  0.0  0.000000  0.0  0.065387
2  0.000000  0.000000  0.0  0.000000  0.0  0.000000
3  0.098929  0.073639  0.0  0.000000  0.0  0.000000
4  0.091348  0.000000  0.0  0.089383  0.0  0.000000

In [47]:
dd2['P1'].unique()

array([0.        , 0.05621645, 0.09892893, 0.09134809, 0.16331508,
       0.04441698, 0.08748263, 0.05950344, 0.07101919, 0.09476676,
       0.07870291, 0.06379828, 0.03642902, 0.05325092, 0.09430258,
       0.05720333, 0.05757048, 0.07156301, 0.05208472, 0.11173485,
       0.08931669, 0.16783227, 0.05185563, 0.07625063, 0.12428352,
       0.09410068, 0.14725043, 0.07841789, 0.15325194, 0.04753135,
       0.05723573, 0.10339474, 0.06513944, 0.05136481, 0.09635046,
       0.21285265, 0.20636445, 0.04729834])

In [48]:
dd2['P2'].unique()

array([0.        , 0.07363877, 0.05663218, 0.0476163 , 0.06795483,
       0.02846955, 0.04218203, 0.04380053, 0.04355735, 0.06402972,
       0.04154836, 0.06362433, 0.06421736, 0.0730894 , 0.0351862 ,
       0.02667758, 0.08019181, 0.09588717, 0.04865065, 0.0591893 ,
       0.11855502, 0.1195312 , 0.19188069, 0.03677928, 0.08380147,
       0.15291455, 0.05312714, 0.03905853, 0.13348046, 0.12792859,
       0.15223133, 0.05480853, 0.04708933, 0.06363658, 0.11153877,
       0.0508999 , 0.04669495, 0.11861737, 0.08140991, 0.05718907,
       0.03630002, 0.04630966, 0.19190441, 0.41906768])

In [49]:
dd2['P3'].unique()

array([0.        , 0.24226956, 0.12352868, 0.11331465, 0.32107063,
       0.1214387 , 0.20398569, 0.1271005 , 0.10899252, 0.10589285])

In [50]:
dd2['P4'].unique()

array([0.        , 0.08938256, 0.08560027, 0.06949107, 0.0690511 ,
       0.06969471, 0.07932349, 0.06242554, 0.11293554, 0.0971647 ,
       0.05073986, 0.09207592, 0.08529916, 0.1308212 , 0.24317287,
       0.06072475, 0.06206696, 0.12557282, 0.10413635, 0.0801917 ,
       0.10096206])

In [51]:
dd2['P5'].unique()

array([0.        , 0.14376293, 0.18075083, 0.11809997, 0.16568426,
       0.11481062, 0.13557636, 0.08965547, 0.17766523, 0.22914145,
       0.28113247, 0.05596046, 0.11138645])

In [52]:
dd2['P6'].unique()

array([0.        , 0.06538724, 0.09034017, 0.05166287, 0.16326138,
       0.24374385, 0.18585184, 0.07513423, 0.27852678, 0.07090329,
       0.09197434, 0.08260479, 0.0820818 , 0.08284687, 0.0942927 ,
       0.08345724, 0.04237181, 0.12656511, 0.05709918, 0.06653511,
       0.23572347, 0.05193837, 0.06058148, 0.07064872, 0.13230316,
       0.07893891, 0.08868966, 0.06935386, 0.12011949, 0.10032779,
       0.28064879, 0.10573724, 0.2532091 , 0.05528531, 0.06657279,
       0.07218417, 0.07377967, 0.07576586, 0.05974413, 0.20360439,
       0.12378802, 0.25947032, 0.33325511, 0.22260752])

### Conclusion : We cannot set threshold value for this model. All the values are below 0.2 and most of them are below 0.01.